#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME:=suchai
EXTRA_COMPONENT_DIRS:=$(shell pwd)/src/os $(shell pwd)/src/drivers/esp32/sch_components $(shell pwd)/src/system

include $(IDF_PATH)/make/project.mk
