#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := suchai
SRCDIRS:=$(shell pwd)/src/system
EXTRA_COMPONENT_DIRS:=$(shell pwd)/src/os

include $(IDF_PATH)/make/project.mk
